### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by rickdroce** [inspheric/nova-defaultable-fields#1]
Hi mate!

Nice idea for this plugin, I was thinking about this when i found your plugin.

I followed the guide in the readme by adding the `HasDefaultableFields` in the base resource class of nova but it seems that nothing happens, no errors ecc ecc.

Is it the right way to install the plugin? I also see that the method `default()` that you use in the resources is from another class that doesn't have anything to do with the trait

**Comment by kitbs** [comment]
Hi @rickdroce

The trait intercepts the fillFields() method on the resource in order to save values to the cache for when you are using defaultLast(). If you don't have any fields with defaultLast(), it won't do anything. (If you don't intend to use defaultLast() at all, you can even leave the trait off.)

The other class is the one that does all of the populating on the fields.

**Comment by rickdroce** [comment]
Ok thank you for the explanation, but I'm still not getting it to work.
If I try to call the `default()` method to a nova field as it's written inside the docs, nothing happens. Can't really tell what I'm doing wrong :/

e.g. `Text::make('Name')->default('default name')`

**Comment by kitbs** [comment]
Yes, that is all you should need to do.

So when you click "Create" for the resource that this field is on, the value 'default name' is not being populated in the form? Is that right?
