### ISSUE TITLE
Validation error in Nova 3.6.0

### ISSUE THREAD

**Issue by Grayda** [inspheric/nova-defaultable-fields#14]
I've just updated to Nova 3.6.0 and the package is still working for the most part, however it throws validation errors when you create a new resource.

To replicate this:

1. Install Nova 3.6.0 and Defaultable 1.2. Set up some resources and make some fields defaultable. 
2. Create something like you normally would and save it. The resource should save correctly.
3. Create another item. Even though the fields are pre-filled, you'll get validation errors about the field being blank, even though it's not.

![image](https://user-images.githubusercontent.com/4891563/81898931-03214d00-95fd-11ea-9058-2f14f776380b.png)

If you pick another value and then go back to the original value, it works fine, but it's just when the form has loaded and the defaults are set, that you get the validation error.

**Comment by kitbs** [comment]
Hi @Grayda 

Unfortunately, Nova's new `default()` method released in v3.4.0 completely bypasses the `default()` method in this package, so I don't think the issue you are having is due to this package. I am currently working out whether I can refactor and keep some parts of this package or whether it should be deprecated.

Can I confirm, are the Platform and Type fields in your screenshot `Select` or `BelongsTo` fields? I have had trouble when testing Nova's own `default()` method on `BelongsTo` and `MorphTo` fields particularly and am planning to raise an issue with the Nova team.

Can you please try to uninstall this package and let me know if the behaviour is the same?

**Comment by kitbs** [comment]
Issue raised with Nova team at https://github.com/laravel/nova-issues/issues/2608.

Behaviour is not related to this package.

**Comment by Grayda** [comment]
Yep it was a BelongsTo field, being used with `defaultLast()`. I'll keep an eye on the issue you referenced for more info (I wasn't even aware there was a `default()` in Nova, as I was a few versions behind).

Thanks for that :)
