### ISSUE TITLE
Not working 2.0.6

### ISSUE THREAD

**Issue by bsormagec** [inspheric/nova-defaultable-fields#8]
Not workin 2.0.6 any idea?

**Comment by kitbs** [comment]
Hi @bsormagec

It's working fine in 2.0.6 for me. Can you give me more detail of what you have tried, what is or isn't working, whether you have any error messages?

**Comment by bsormagec** [comment]
Its not returning default value i checked step by step functions but when i use ->defaultLast() method its not doing anything. I can check and give you more information.

**Comment by kitbs** [comment]
So you have used `defaultLast()` on a field, created one resource and entered your own value on that field, then when you create a second resource the value is not being populated again?

Can you confirm you have added the trait `Inspheric\NovaDefaultable\HasDefaultableFields` to your resource? Instructions are in the README under [Installation](https://github.com/inspheric/nova-defaultable-fields#installation).

I can confirm the behaviour works in my fresh install of 2.0.6.

**Comment by bsormagec** [comment]
I checked many times but not working :( I dont understand whats wrong

**Comment by kitbs** [comment]
Hi @bsormagec 

I don't understand what is wrong either because you have not explained what you have tried to do or what you have checked many times. If you want me to try and help with your problem, you will need to give me more information to go on.

Are you using `defaultLast()` on a Resource or on an Action?

Does the start of your file `app\Nova\Resource.php` look like this?
```php
<?php

namespace App\Nova;

use Laravel\Nova\Resource as NovaResource;
use Laravel\Nova\Http\Requests\NovaRequest;

use Inspheric\NovaDefaultable\HasDefaultableFields; // <-- Add this line

abstract class Resource extends NovaResource
{
    use HasDefaultableFields; // <-- Add this line
```

Have you defined the field on your resource or action like this?
```php
Text::make('Name')
    ->defaultLast(),
```

What field type are you trying to use it on? Is it a standard Nova field like Text/ Number/ Textarea, etc.? Or is it a custom field type of your own or from another package?

Have you tried just using `default('TEST')` on the same field and does the value 'TEST' get populated when you create a new resource?

Can you tell me step by step what you are doing in the UI to test that it does not work? You could also send a screen capture if this is easier.

**Comment by bsormagec** [comment]
Yes i added like it and added trait to resource you can see here .

https://www.dropbox.com/s/ahzxgrgyiwdqf75/Screenshot%202019-06-27%2020.17.54.png?dl=0

but not working :(

**Comment by kitbs** [comment]
Hi @bsormagec 

Thanks for sending the screenshot; you have set it up correctly.

There are other questions from my previous comment that you have not answered:
- What field type are you trying to use it on? Is it a standard Nova field like Text/ Number/ Textarea, etc.? Or is it a custom field type of your own or from another package?
- Have you tried just using `default('TEST')` on the same field and does the value 'TEST' get populated when you create a new resource?
- Can you tell me step by step what you are doing in the UI to test that it does not work?

Other things you could think about:
- Are the traits in your screenshot the only ones you are using on the actual resource? Looking at their code, Breadcrumbs and SearchesRelations won't affect the behaviour, but if you have any other trait that also overrides the `fillFields()` method this could be interfering.
- Are you familiar with https://laravel.com/docs/5.8/telescope or https://github.com/barryvdh/laravel-debugbar or something else that you could use to inspect the cache? If so, can you tell me whether there are any events (hit, miss, set) for any cache key beginning with `default_last.*`?

Thanks
